### ISSUE TITLE
Missing Type Annotations

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_PCF8523#23]
There are missing type annotations for some functions in this library.

The `typing` module does not exist on CircuitPython devices so the import needs to be wrapped in try/except to catch the error for missing import. There is an example of how that is done here:

```python
try:
    from typing import List, Tuple
except ImportError:
    pass
```

Once imported the typing annotations for the argument type(s), and return type(s) can be added to the function signature. Here is an example of a function that has had this done already:

```python
def wrap_text_to_pixels(
    string: str, max_width: int, font=None, indent0: str = "", indent1: str = ""
) -> List[str]:
```
If you are new to Git or Github we have a guide about contributing to our projects here: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

There is also a guide that covers our CI utilities and how to run them locally to ensure they will pass in Github Actions here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code In particular the pages: `Sharing docs on ReadTheDocs` and `Check your code with pre-commit` contain the tools to install and commands to run locally to run the checks.

If you are attempting to resolve this issue and need help, you can post a comment on this issue and tag both @foamyguy and @kattni or reach out to us on Discord: https://adafru.it/discord in the `#circuitpython-dev` channel.

The following locations are reported by mypy to be missing type annotations:

- [ ] adafruit_pcf8523.py:139
- [ ] adafruit_pcf8523.py:160

**Comment by FoamyGuy** [comment]
closed by #24

**Comment by raquo** [comment]
I see this was fixed a while ago, but somehow, when I run mypy in my project that depends on this package, the line `from adafruit_pcf8523.pcf8523 import PCF8523` causes the following mypy error:

_error: Skipping analyzing "adafruit_pcf8523.pcf8523": module is installed, but missing library stubs or py.typed marker  [import-untyped]_

Does this library need some additional config to avoid this error, like this `py.typed` thing that it mentions? Other Adafruit libraries' typings seem to be working fine, it's just this one library, for me.

(python 3.10, mypy 1.8.0, adafruit-circuitpython-pcf8523 2.0.1)

**Comment by tekktrik** [comment]
I believe the `py.typed` tagfile is needed in the package to truly mark it as typed, although I don't think most other packages have it.  Out of curiosity, which ones is it saying are fine on your end?

**Comment by raquo** [comment]
OTOH, I am also using the Servo class from
https://github.com/adafruit/Adafruit_CircuitPython_Motor and mypy is not
complaining about it.

It does not seem to have a `py.typed` file either (I assume it would be
visible on GitHub). I am not sure what is different about it...
